backend:
  name: git-gateway
  branch: master

publish_mode: editorial_workflow

media_folder: static/img
public_folder: /img

collections:
  - label: "Settings"
    name: "settings"
    delete: false
    editor:
      preview: false
    files:
      - label: "Footer"
        name: "footer"
        file: "data/footer.json"
        description: "Footer Settings"
        fields:
          - name: "footer_text"
            label: "Footer Text"
            widget: "string"
      - label: "Header"
        name: "header"
        file: "data/header.json"
        description: "Header Settings"
        fields:
          - name: "navigation_links"
            label: "Navigation Links"
            widget: list
            fields:
              - {label: "Link", name: "link", widget: "string"}
              - {label: "Link Name", name: "link_name", widget: "string"}
  - label: "Pages"
    name: "pages"
    delete: false
    editor:
      preview: false
    files:
      - name: "home"
        label: "Home"
        file: "data/home.json"
        description: "Gallery Images"
        fields:
          - name: image
            label: Image
            widget: list
            fields:
              - {label: "Alt", name: "alt", widget: "string"}
              - {label: "Image", name: "image", widget: "image"}
      - name: "imprint"
        label: "Impressum"
        file: "data/imprint.json"
        description: "Imprint content"
        fields:
          - name: "body"
            label: "Inhalt"
            widget: markdown
      - name: "about_me"
        label: "Zu meiner person"
        file: "data/about_me.json"
        description: "About me content"
        fields:
          - name: "body"
            label: "Inhalt"
            widget: markdown